Repository FullScreenShenanigans/FullScreenPokemon, pull requests merged in 2018-03, with the labels that each got.

#633 Added an API for giving a Pokemon a new move
  src/components/MoveAdder.ts
Labels: PR: Ready to Merge

#639 Fixed Oak Cutscene Bug
  src/components/cutscenes/OakIntroPokemonChoiceCutscene.ts
Labels: PR: Structural Changes Requested

#645 Fixed an issue where a Pokemon's status would not be correctly displayed.
  src/components/menus/Pokemon.ts
Labels: PR: Structural Changes Requested

#638 Added dialog for teaching Pokemon new moves
  src/components/MoveAdder.ts
Labels: PR: Waiting for Reviewer

#654 Added PP functionality
  src/components/equations/ItemEffects.ts
Labels: PR: Structural Changes Requested

#658 Ledge fix
  src/components/Collisions.ts
  src/creators/createObjectMaker.ts
  src/creators/createPixelRender.ts
  src/creators/mapsLibrary/PewterCity.ts
  src/creators/mapsLibrary/Route1.ts
  src/creators/mapsLibrary/Route2.ts
  src/creators/mapsLibrary/Route22.ts
  src/creators/mapsLibrary/ViridianCity.ts
Labels: PR: Stylistic Changes Requested

#656 Added logic for adding battle stats
  src/components/equations/ItemEffects.ts
Labels: PR: Stylistic Changes Requested

#652 Added a unit test for the new move API
  src/FullScreenPokemon.ts
  src/components/MoveAdder.test.ts
  src/components/MoveAdder.ts
Labels: PR: Stylistic Changes Requested
